#!/bin/bash

#自动语言
uci set luci.main.lang=auto
uci commit luci

#时区设置
uci set system.@system[0].zram_comp_algo='lz4'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci commit system

#PASSWALL
[ -f '/usr/share/v2ray/geoip.dat' ] && uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_subscribe[0].ss_aead_type='shadowsocks-rust'
uci set passwall.@global_delay[0].start_delay='5'
uci set passwall.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall

#SING-BOX
uci set network.tun0=interface
uci set network.tun0.proto='none'
uci set network.tun0.device='tun0'
uci commit network
zone_id=$(uci add firewall zone)
uci set firewall.@zone[-1].name='sing_box'
uci set firewall.@zone[-1].input='ACCEPT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='ACCEPT'
uci set firewall.@zone[-1].masq='1'
uci set firewall.@forwarding[-1].src='sing_box'
uci set firewall.@forwarding[-1].dest='lan'
uci add_list firewall.${zone_id}.network='tun0'
uci commit firewall

#Feeds 更换镜像源
sed -i 's,23.05,OPENWRT_VER,g' /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

#uhttpd 设置
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
#uci set uhttpd.main.tcp_keepalive=0
#uci set uhttpd.main.script_timeout=65535
#uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

#在防火墙默认开启全锥形 NAT
uci set firewall.@defaults[0].fullcone='2'
[ -f '/sbin/fw4' ] && uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

#默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci commit network

#通用即插即用
uci set upnpd.config.enabled='1'
uci set upnpd.config.force_forwarding='1'
#uci del upnpd.config.use_stun
#uci del upnpd.config.stun_host
uci commit upnpd

#MosDNS广告源
uci set mosdns.config.adblock='1'
uci add_list mosdns.config.ad_source='https://github.com/QiuSimons/openwrt-mos/raw/master/dat/serverlist.txt'
uci commit mosdns

#定时清理
(crontab -l | sed '/find \/tmp/d'; echo "0 0 1 * * find /tmp -type f \( -name \"*.log\" -o -name \"*.txt\" \) -exec sh -c 'rm {} && touch {}' \;") | sed '/^$/d' | crontab -

#rpcd
[ $(uci -q get rpcd.@rpcd[0].timeout) -lt 60 ] && uci set rpcd.@rpcd[0].timeout=60 && uci commit rpcd

#清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
