#!/bin/bash

dir_list=$(cat ~/.bash_history | grep '^cd ' | sort | uniq -c | sort -rn | awk '{print $3}' | grep $1)
dir_list_nospace=$(echo $dir_list | sed 's/ //g')
if [[ $dir_list == "" ]]; then
    echo "Plese type a keyword and retry. exp: j 2p4"
elif [[ $dir_list == $dir_list_nospace ]]; then
    cd $dir_list
else
    echo $dir_list
fi