#!/bin/sh
#
# 首次启动后执行，进行一些默认设置。运行后会自动删除此脚本。
#

# 默认密码 ( password )
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

# 调整 Emmc 分区大小
sed -e 's/^ROOT1=.*/ROOT1="1024"/' -e 's/^ROOT2=.*/ROOT2="1024"/' -i /usr/sbin/openwrt-install-amlogic

# Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# nginx 设置
sed -i 's/deny all/allow all/g' /etc/nginx/restrict_locally
uci delete nginx._redirect2ssl.return
uci delete nginx._redirect2ssl.include
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci commit nginx
/etc/init.d/nginx restart

# Cpufreq 设置
uci batch << EOI
set amlogic.armcpu.governor0='schedutil'
set amlogic.armcpu.minfreq0='500000'
set amlogic.armcpu.maxfreq0='1512000'
EOI
uci commit amlogic

# 启用 KMS 服务器
uci batch << EOI
set vlmcsd.config.enabled='1'
set vlmcsd.config.auto_activate='1'
set vlmcsd.config.internet_access='1'
EOI
uci commit vlmcsd

# MosDNS
uci set mosdns.config.log_level='error'
uci commit mosdns

# Feeds 更换镜像源
sed -i 's#downloads.immortalwrt.org#mirror.nju.edu.cn/immortalwrt#g' /etc/apk/repositories.d/distfeeds.list
sed -i 's#mirrors.vsean.net/openwrt#mirror.nju.edu.cn/immortalwrt#g' /etc/apk/repositories.d/distfeeds.list

# 默认开启 Packet Steering
uci set network.globals.packet_steering='2'
uci set network.globals.steering_flows='256'
uci commit network

# 通用即插即用
uci set upnpd.config.enabled='1'
uci commit upnpd

# bandix
uci set bandix.general.log_level='error'
uci commit bandix

# 计划任务
uci set system.@system[0].cronloglevel="9"
uci commit system
/etc/init.d/cron restart

# V2rayA
[ -d /usr/share/xray ] || mkdir -p /usr/share/xray
[ -f /usr/share/v2ray/geoip.dat ] && ln -sf /usr/share/v2ray/geoip.dat /usr/share/xray/geoip.dat
[ -f /usr/share/v2ray/geosite.dat ] && ln -sf /usr/share/v2ray/geosite.dat /usr/share/xray/geosite.dat

# Podman
sed -i '/firewall_driver/c\firewall_driver = "nftables"' /etc/containers/containers.conf
sed -i '/^graphroot/c\graphroot = "/mnt/mmcblk2p4/containers/storage"' /etc/containers/storage.conf

# Flag packages (禁止更新)
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# 禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop
/etc/init.d/sing-box disable 2>/dev/null
/etc/init.d/sing-box stop
/etc/init.d/podman disable 2>/dev/null
/etc/init.d/podman stop

# openwr_release 写入编译日期
sed -i '/BUILD_DATE/d' /etc/openwrt_release
echo "BUILD_DATE='build_date'" >> /etc/openwrt_release

# 清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
