#!/bin/bash

# Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# PASSWALL
[ -f '/usr/share/v2ray/geoip.dat' ] && uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_subscribe[0].ss_aead_type='shadowsocks-rust'
uci set passwall.@global_delay[0].start_delay='5'
uci set passwall.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall

# uhttpd 设置
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
#uci set uhttpd.main.tcp_keepalive=0
#uci set uhttpd.main.script_timeout=65535
#uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

# nginx 设置
sed -i 's,deny all,allow all,g' /etc/nginx/restrict_locally
uci delete nginx._redirect2ssl.return
uci delete nginx._redirect2ssl.include
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci commit nginx
/etc/init.d/nginx restart

# 在防火墙默认开启全锥形 NAT 以及关闭 Flow Offloading 并开启 SFE
uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].brcmfullcone='1'
uci set firewall.@zone[1].fullcone4='1'
uci set firewall.@zone[1].fullcone6='1'
uci set firewall.@defaults[0].natflow='0'
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall
/etc/init.d/autocore restart

# 默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci commit network

# 通用即插即用
uci set upnpd.config.enabled='1'
uci set upnpd.config.force_forwarding='1'
#uci del upnpd.config.use_stun
#uci del upnpd.config.stun_host
uci commit upnpd

# 定时清理
(crontab -l | sed '/find \/tmp/d'; echo "0 0 1 * * find /tmp -type f \( -name \"*.log\" -o -name \"*.txt\" \) -exec sh -c 'rm {} && touch {}' \;") | sed '/^$/d' | crontab -

# rpcd
[ $(uci -q get rpcd.@rpcd[0].timeout) -lt 60 ] && uci set rpcd.@rpcd[0].timeout=60 && uci commit rpcd

# OpenClash 设置
echo "/etc/openclash/" >> /etc/sysupgrade.conf && cat /etc/sysupgrade.conf | sort | uniq > /tmp/tmp_sysupgrade_conf && cat /tmp/tmp_sysupgrade_conf > /etc/sysupgrade.conf
[ -f /usr/share/v2ray/geosite.dat ] && [ -d /etc/openclash ] && ln -sf /usr/share/v2ray/geosite.dat /etc/openclash/GeoSite.dat

# Flag packages (禁止更新)
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# 禁用Docker自动启动
uci set dockerd.globals.auto_start='0'
uci commit dockerd

# 禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fastcgi stop
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php7-fpm stop
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fastcgi stop
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/php8-fpm stop
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnbridge stop
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnserver stop
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/softethervpnclient stop
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/socat disable 2>/dev/null
/etc/init.d/socat stop
/etc/init.d/fa-rk3399-pwmfan disable 2>/dev/null
/etc/init.d/fa-rk3399-pwmfan stop
/etc/init.d/fa-rk3328-pwmfan disable 2>/dev/null
/etc/init.d/fa-rk3328-pwmfan stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop
/etc/init.d/shortcut-fe enable 2>/dev/null
/etc/init.d/shortcut-fe start
/etc/init.d/qemu-ga disable 2>/dev/null
/etc/init.d/qemu-ga stop
/etc/init.d/sing-box disable 2>/dev/null
/etc/init.d/sing-box stop

chmod 0755 /etc/init.d/*

# 清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
