#!/bin/sh

# 时区设置
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci commit system

# Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# PASSWALL
[ -f '/usr/share/v2ray/geoip.dat' ] && uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_subscribe[0].ss_aead_type='shadowsocks-rust'
uci set passwall.@global_delay[0].start_delay='5'
uci set passwall.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall

# Feeds 更换镜像源
sed -i 's,downloads.openwrt.org,mirrors.tuna.tsinghua.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# uhttpd 设置
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci commit uhttpd
/etc/init.d/uhttpd restart

# 默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci commit network

# 通用即插即用
uci set upnpd.config.enabled='1'
uci commit upnpd

# OpenClash
[ -f /usr/share/v2ray/geosite.dat ] && [ -d /etc/openclash ] && ln -sf /usr/share/v2ray/geosite.dat /etc/openclash/GeoSite.dat
[ -f /usr/share/v2ray/geosite.dat ] && [ -d /etc/openclash ] && ln -sf /usr/share/v2ray/geoip.dat /etc/openclash/GeoIP.dat

# V2rayA
[ -f /usr/share/v2ray/geoip.dat ] && ln -sf /usr/share/v2ray/geoip.dat /usr/share/xray/geoip.dat
[ -f /usr/share/v2ray/geosite.dat ] && ln -sf /usr/share/v2ray/geosite.dat /usr/share/xray/geosite.dat

# 定时清理
(crontab -l | sed '/find \/tmp/d'; echo "0 0 1 * * find /tmp -type f \( -name \"*.log\" -o -name \"*.txt\" \) -exec sh -c 'rm {} && touch {}' \;") | sed '/^$/d' | crontab -

# rpcd
[ $(uci -q get rpcd.@rpcd[0].timeout) -lt 60 ] && uci set rpcd.@rpcd[0].timeout=60 && uci commit rpcd

# Flag packages (禁止更新)
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# 禁用Docker自动启动
uci set dockerd.globals.auto_start='0'
uci commit dockerd

# docker 镜像站点
if [ -f /etc/config/dockerd ]; then
    uci del dockerd.globals.registry_mirrors
    uci add_list dockerd.globals.registry_mirrors='https://dockerpull.com'
    uci add_list dockerd.globals.registry_mirrors='https://dockerproxy.net'
    uci add_list dockerd.globals.registry_mirrors='https://docker.m.daocloud.io'
    uci commit dockerd
fi

# 禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/sing-box disable 2>/dev/null
/etc/init.d/sing-box stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop
/etc/init.d/dockerd disable 2>/dev/null
/etc/init.d/dockerd stop

# 清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
