#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/sing-box 
RES_DIR=/etc/sing-box/ 
CONF=./config.json   

start_service() {
    procd_open_instance
    procd_set_param command $PROG run -D $RES_DIR -c $CONF
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance
    ip rule add fwmark 1 table 100
    ip route add local 0.0.0.0/0 dev lo table 100
    nft -f /etc/sing-box/nftables-ip46.conf
    nft add chain inet sing-box docker { type nat hook prerouting priority -100 \; }
    nft add rule inet sing-box docker ip saddr != {172.17.0.0/16} return
    echo "sing-box is started!"
}

stop_service() {
    service_stop $PROG
    ip rule del fwmark 1 table 100
    ip route del local 0.0.0.0/0 dev lo table 100
    nft delete table inet sing-box
    echo "sing-box is stopped!"
}

reload_service() {
    stop
    sleep 2s
    echo "sing-box is restarted!"
    start
}