
config sing-box 'main'
	option enabled '0'
	option workdir '/etc/sing-box'
	option fuck_quic '1'
	option common_ports '0'
	option pass_cn_ip '0'

config sing-box 'profile'
	option profile 'sub:1'
	list prefix '[provider1] '
	list url ''
	list prefix '[provider2] '
	list url ''
	option auto_restart '1'
	option restart_cron '0 5 * * *'

config sing-box 'basic'
	option log_level 'warn'
	option log_file '/var/log/sing-box.log'
	option external_controller_port '9900'
	option external_ui 'ui'
	option secret 'ffuqiangg'
	option ui_name 'zashboard'
	option default_mode 'rule'
	option store_rdrc '0'
	option tproxy_port '10105'
	option mixed_port '2881'
	option dns_port '2053'
	option redirect_port '2331'

config sing-box 'advanced'
	option override '1'
	option main_dns_type 'https'
	option main_dns_server 'dns.google'
	option china_dns_type 'h3'
	option china_dns_server '223.5.5.5'
	list ad_ruleset 'https://testingcf.jsdelivr.net/gh/ffuqiangg/sing-box-adsruleset@main/rule/adguard-dns-filter.srs'
	option nodes_filter ''
	option area ''
	option bypass ''
