set nocompatible                    " use vim defaults
set showcmd                         " display incomplete commands
set showmatch                       " jump to matchs when entering parenthes
set matchtime=1                     " tenths of a secend to show the matching parenthes
set backspace=indent,eol,start      " make that backspace key work the way it should
set textwidth=0                     " don't wrap lines by default
set ruler                           " show the current row and column
set number                          " show line numbers
set wildmenu                        " show list instead of just completing
set splitright                      " put new split window in right
set nobackup                        " don't keep a backup file
set fillchars=vert:│                " change vertsplit character

set nowrap                          " line exceed screen don't wrap
set sidescroll=1                    " line exceed screen cursor smooth scrolling
set laststatus=2                    " always show statusline
" set numberwidth=5                   " line number width configure 

set novisualbell                    " turn off visualbell
set noerrorbells                    " turn off errorbell

set hlsearch                        " highlight searchs
set incsearch                       " do incremental searching
set ignorecase                      " ignore case when searching
set smartcase                       " no ignorecase if Uppercase char present

set autoindent                      " always set autoindenting on
set smartindent                     " indent works for c-like
set tabstop=4                       " <Tab> width look for
set expandtab                       " expand <Tab> as spaces
set softtabstop=4                   " spaces number when insert <Tab>
set shiftround                      " indent not to multiple of 'shiftwidth'
set shiftwidth=4                    " number of spaces to use for (auto)indent

" Specify file config
" filetype plugin off
" autocmd Filetype yaml set tabstop=2 shiftwidth=2 softtabstop=2

" User Interface customize
set t_Co=16                         " enable 16 colors
hi TabLine ctermfg=8 ctermbg=NONE cterm=NONE
hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
hi! link TabLineFill TabLine
hi LineNr ctermfg=8
hi Pmenu ctermfg=15 ctermbg=8
hi PmenuSel ctermfg=0 ctermbg=4
hi VertSplit ctermfg=8 ctermbg=NONE cterm=NONE
hi StatusLine ctermfg=0 ctermbg=7 cterm=NONE
hi StatusLineNC ctermfg=8 ctermbg=7 cterm=NONE
hi IncSearch ctermfg=0 ctermbg=3 cterm=NONE
hi Search ctermfg=0
hi Visual ctermbg=NONE cterm=reverse

" Statusline configure
set statusline=%h%m%r%w\ %<%f\ \ %P\ \(%l,%c\)%=\ %{&ft}\[%{&fenc}\|%-7(%{&ff}\]%)
