#!/bin/bash

passwd root << EOI
password
password
EOI

uci set network.lan.ipaddr='192.168.1.99'
uci commit network

uci set luci.main.lang=auto
uci commit luci

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

ln -sf /sbin/ip /usr/bin/ip

sed -i "s/# //g" /etc/opkg/distfeeds.conf

[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

# Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# PASSWALL
[ -f '/usr/share/v2ray/geoip.dat' ] && uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_subscribe[0].ss_aead_type='shadowsocks-rust'
uci set passwall.@global_delay[0].start_delay='5'
uci set passwall.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall

# 默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci commit network

# 通用即插即用
uci set upnpd.config.enabled='1'
uci commit upnpd

# MosDNS
echo 'account.synology.com
ddns.synology.com
checkip.synology.com
checkip.dyndns.org
checkipv6.synology.com
ntp.aliyun.com
cn.ntp.org.cn
ntp.ntsc.ac.cn' >> /root/etc/mosdns/rule/whitelist.txt

# OpenClash
[ -f /usr/share/v2ray/geosite.dat ] && [ -d /etc/openclash ] && ln -sf /usr/share/v2ray/geosite.dat /etc/openclash/GeoSite.dat
[ -f /usr/share/v2ray/geosite.dat ] && [ -d /etc/openclash ] && ln -sf /usr/share/v2ray/geoip.dat /etc/openclash/GeoIP.dat

# V2rayA
[ -f /usr/share/v2ray/geoip.dat ] && ln -sf /usr/share/v2ray/geoip.dat /usr/share/xray/geoip.dat
[ -f /usr/share/v2ray/geosite.dat ] && ln -sf /usr/share/v2ray/geosite.dat /usr/share/xray/geosite.dat

# 定时清理
(crontab -l | sed '/find \/tmp/d'; echo "0 0 1 * * find /tmp -type f \( -name \"*.log\" -o -name \"*.txt\" \) -exec sh -c 'rm {} && touch {}' \;") | sed '/^$/d' | crontab -

# Flag packages (禁止更新)
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# 禁用 Docker 自动启动
uci set dockerd.globals.auto_start='0'
uci commit dockerd

# 停用服务
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/sing-box disable 2>/dev/null
/etc/init.d/sing-box stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop
/etc/init.d/dockerd disable 2>/dev/null
/etc/init.d/dockerd stop

chmod 0755 /etc/init.d/*

# 清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit0